### ISSUE TITLE
Wrong colors displayed in spatial-js-demo example

### ISSUE THREAD

**Issue by pklimai** [mipt-npm/dataforge-vis#2]
When running the spatial-js-demo example, the following logs are seen in the JS Console:
```
three.module.js?88cf:8141 THREE.Color: Unknown color #8080
three.module.js?88cf:8141 THREE.Color: Unknown color #ff
```
Also some colors look wrong, e.g. extruded shape is white rather than teal. I fixed this by prepending extra zeros in Colors/rgbToString(), but need to make sure this does not break anything else.

**Comment by altavir** [comment]
Thanks, I though that I've fixed that. But maybe I am wrong, so I will check again.

**Comment by altavir** [comment]
Confirmed, fixed.
